# Generated by Django 3.0.8 on 2020-08-13 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('testimonial_1', models.TextField()),
                ('testimonial_2', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cost_includes', models.TextField()),
                ('cost_excludes', models.TextField()),
                ('daily_schedule', models.TextField()),
                ('optional_extras', models.TextField()),
                ('card_pic_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_pic_image', to='file.FileOnS3')),
                ('retreat_image_gallery', models.ManyToManyField(related_name='image_gallery', to='file.FileOnS3')),
                ('retreat_main_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retreat_main_image', to='file.FileOnS3')),
            ],
        ),
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('retreat_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retreat.RetreatLocation')),
            ],
        ),
    ]
