# Generated by Django 3.0.8 on 2020-08-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatlocation',
            name='cost_excludes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retreatlocation',
            name='optional_extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retreatlocation',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
