# Generated by Django 3.0.8 on 2020-08-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0002_auto_20200825_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatlocation',
            name='cost_includes',
            field=models.TextField(help_text='eg. Shared accommodation: All veggie meals: All yoga...'),
        ),
        migrations.AlterField(
            model_name='retreatlocation',
            name='daily_schedule',
            field=models.TextField(help_text='eg. 7am - Breakfast: 8am - Yoga...'),
        ),
        migrations.AlterField(
            model_name='retreatlocation',
            name='description',
            field=models.TextField(help_text='Add a new line to create a new paragraph on the page'),
        ),
        migrations.AlterField(
            model_name='retreatlocation',
            name='optional_extras',
            field=models.TextField(blank=True, help_text='eg. Sauna: Massage: Running...', null=True),
        ),
    ]
