# Generated by Django 3.0.8 on 2020-07-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0002_retreat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
