# Generated by Django 3.0.8 on 2020-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0003_auto_20200728_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
