# Generated by Django 3.0.8 on 2020-08-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('retreat', '0004_retreat_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreatlocation',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.FileOnS3'),
        ),
    ]
