# Generated by Django 3.0.8 on 2020-08-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image_s3',
            new_name='image',
        ),
    ]
