# Generated by Django 3.0.8 on 2020-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_recipe_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
