# Generated by Django 3.0.8 on 2020-09-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('recipe', '0006_auto_20200902_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.FileOnS3'),
        ),
    ]
