# Generated by Django 3.0.8 on 2020-09-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('recipe', '0007_recipecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.FileOnS3'),
        ),
    ]
