# Generated by Django 3.0.8 on 2020-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20200902_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(help_text='Separate method steps by adding : inbetween e.g Wash rice: cover with water and cook'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_intro',
            field=models.TextField(blank=True, help_text='Separate method steps by adding newline inbetween paragraphs'),
        ),
    ]
